version: '3.9'

services:
    postgres:
        image: postgres:latest
        container_name: psql-db
        restart: always
        environment:
            - POSTGRES_DB=${pgsql_db}
            - POSTGRES_PASSWORD=${pgsql_password} # must for superuser password
            - POSTGRES_USER=${pgsql_user} # the new superuser
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d ${pgsql_db} -U ${pgsql_user}"]
            interval: 1s
            timeout: 5s
            retries: 10
        ports:
            - '5432:5432'
        volumes:
            - pg-data:/var/lib/postgresql/data
            - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql


    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin4
        restart: always
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            - PGADMIN_DEFAULT_EMAIL=${pgadmin_email}
            - PGADMIN_DEFAULT_PASSWORD=${pgadmin_password}
        ports:
            - "8989:80"

# use until real smtp server is configured, url to check mails http://localhost:5000/
    smtp4dev:
        image: rnwood/smtp4dev:v3
        container_name: smtp4dev
        restart: always
        ports:
            - '5555:80'
            - '25:25'
            - '143:143'
        volumes:
            - smtp4dev-data:/smtp4dev
        environment:
            - ServerOptions__HostName=smtp4dev

    redis:
        image: redis/redis-stack:latest
        container_name: redis-stack
        restart: always
        volumes:
            - redis_data:/data
        environment:
            - REDIS_ARGS="--requirepass ${redis_password}"
        ports:
            - 6379:6379
            - 3333:8001

volumes:
    pg-data:
    smtp4dev-data:
    redis_data:
    redis_insight_data:
